server:
  port: 8085 # порт, на котором будет запущен наш сервис
  shutdown: graceful # для корректного завершения работы приложения

logging:
  level:
    root: info

spring:
  flyway:
    baseline-on-migrate: true # создаем таблицу flyway_schema_history, если ее нет
    baseline-version: 0 # начальная версия миграции
    enabled: true # включаем flyway
  application:
    name: task-effort-app-name
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver # драйвер для работы с postgres
  jpa:
    hibernate:
      ddl-auto: validate # выключаем автоматическое создание таблиц хибернейтом, т.к. используем flyway
      # оставляем валидацию таблиц
    show-sql: true # показывать sql запросы в консоли
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # диалект для работы с postgres
        format_sql: true # форматировать sql запросы в консоли
    open-in-view: false
